
import { MenuItem, ChallengeQuestion, SafetyQuestion, NotificationItem, KnowledgeCard, KnowledgeItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  {id: "home", icon: "🏠", text: "home", path: "/"},
  {id: "star-challenge", icon: "⭐", text: "challenge", path: "/challenge"},
  {id: "safety-test", icon: "📊", text: "safety", path: "/safety-index"},
  {id: "going-abroad", icon: "✈️", text: "prepare", path: "/prepare"},
  {id: "overseas-help", icon: "🆘", text: "help", path: "/help"},
  {id: "emergency", icon: "🚨", text: "emergency", path: "/emergency"},
  {id: "consular-protection", icon: "🛡️", text: "protection", path: "/protection"},
  {id: "resident-rights", icon: "📜", text: "rights", path: "/rights"},
  {id: "hot-knowledge", icon: "💡", text: "hot-knowledge", path: "/hot-knowledge"},
  {id: "graphics", icon: "🖼️", text: "graphics", path: "/graphics"},
  {id: "past-notifications", icon: "📨", text: "past-notifications", path: "/past-notifications"},
  {id: "events", icon: "📅", text: "events", path: "/events"},
  {id: "resources", icon: "📚", text: "resources", path: "/resources"},
  {id: "safety-card", icon: "🪪", text: "safety-card", path: "/safety-card"},
  {id: "game-zone", icon: "🎮", text: "game-zone", path: "/game-zone"},
  {id: "contact", icon: "📞", text: "contact", path: "/contact"}
];

export const EXTERNAL_LINKS = {
  emergencyHotline: "+85312308",
  consulateFinder: "https://www.fmprc.gov.cn/web/wjb_673085/zwjg_673153/",
};

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  { id: '1', date: '2026-03-02', link: '/notification/1' },
  { id: '2', date: '2026-03-02', link: '/notification/2' },
  { id: '3', date: '2026-02-25', link: '/notification/3' },
  { id: '4', date: '2026-02-02', link: '/notification/4' },
  { id: '5', date: '2026-02-06', link: '/notification/5' },
];

export const KNOWLEDGE_CARDS: KnowledgeCard[] = [
  {
    id: '1',
    image: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=600&q=80',
    link: '/resources'
  },
  {
    id: '2',
    image: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=600&q=80',
    link: '/emergency'
  },
  {
    id: '3',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
    link: '/protection'
  }
];

export const HOT_KNOWLEDGE_LIST: KnowledgeItem[] = [
  { id: '1', titleKey: 'item_1_q', contentKey: 'item_1_a', tags: ['費用', '自理'] },
  { id: '2', titleKey: 'item_2_q', contentKey: 'item_2_a', tags: ['領保人員', '應急'] },
  { id: '3', titleKey: 'item_3_q', contentKey: 'item_3_a', tags: ['定義', '權益'] },
  { id: '4', titleKey: 'item_4_q', contentKey: 'item_4_a', tags: ['使領館', '援助'] },
  { id: '5', titleKey: 'item_5_q', contentKey: 'item_5_a', tags: ['範圍', '安全'] },
  { id: '6', titleKey: 'item_6_q', contentKey: 'item_6_a', tags: ['區別', '服務'] },
  { id: '7', titleKey: 'item_7_q', contentKey: 'item_7_a', tags: ['邊界', '法律'] },
  { id: '8', titleKey: 'item_8_q', contentKey: 'item_8_a', tags: ['責任', '意識'] },
  { id: '9', titleKey: 'item_9_q', contentKey: 'item_9_a', tags: ['12308', '熱線'] },
  { id: '10', titleKey: 'item_10_q', contentKey: 'item_10_a', tags: ['撥打方式', '備份'] },
];

export const QUIZ_DATA: ChallengeQuestion[] = [
  {
    id: 1,
    correctAnswer: 1
  },
  {
    id: 2,
    correctAnswer: 2
  }
];

export const SAFETY_QUESTIONS: SafetyQuestion[] = [
  { id: 1, category: 'health', weight: 10 },
  { id: 2, category: 'crime', weight: 10 },
  { id: 3, category: 'health', weight: 10 },
  { id: 4, category: 'political', weight: 10 },
  { id: 5, category: 'political', weight: 10 },
  { id: 6, category: 'political', weight: 10 },
  { id: 7, category: 'health', weight: 10 },
  { id: 8, category: 'health', weight: 10 },
  { id: 9, category: 'crime', weight: 10 },
  { id: 10, category: 'political', weight: 10 },
];

// Mapped from provided CSV content with added Traditional Chinese names (Macau/TW Standard)
export const COUNTRY_RISK_DATA = [
  { code: "IS", en: "Iceland", cn: "冰島", gpi: 1.095, gti: 0.123, safeIndex: 95, risk: "Low", usRank: 13 },
  { code: "IE", en: "Ireland", cn: "愛爾蘭", gpi: 1.26, gti: 0.233, safeIndex: 83, risk: "Low", usRank: 12 },
  { code: "NZ", en: "New Zealand", cn: "紐西蘭", gpi: 1.282, gti: 0.217, safeIndex: 90, risk: "Low", usRank: 8 },
  { code: "AT", en: "Austria", cn: "奧地利", gpi: 1.294, gti: 0.582, safeIndex: 92, risk: "Low", usRank: 4 },
  { code: "CH", en: "Switzerland", cn: "瑞士", gpi: 1.294, gti: 1.265, safeIndex: 89, risk: "Low", usRank: 1 },
  { code: "SG", en: "Singapore", cn: "新加坡", gpi: 1.357, gti: null, safeIndex: 90, risk: "Low", usRank: 19 },
  { code: "PT", en: "Portugal", cn: "葡萄牙", gpi: 1.371, gti: null, safeIndex: 57, risk: "Low", usRank: 15 },
  { code: "DK", en: "Denmark", cn: "丹麥", gpi: 1.393, gti: 0.72, safeIndex: 94, risk: "Low", usRank: 5 },
  { code: "SI", en: "Slovenia", cn: "斯洛維尼亞", gpi: 1.409, gti: null, safeIndex: 87, risk: "Low", usRank: 32 },
  { code: "FI", en: "Finland", cn: "芬蘭", gpi: 1.42, gti: 0.949, safeIndex: 86, risk: "Low", usRank: 7 },
  { code: "CZ", en: "Czechia", cn: "捷克", gpi: 1.435, gti: 2.906, safeIndex: 88, risk: "Low", usRank: 27 },
  { code: "JP", en: "Japan", cn: "日本", gpi: 1.44, gti: 0.949, safeIndex: 83, risk: "Low", usRank: 16 },
  { code: "MY", en: "Malaysia", cn: "馬來西亞", gpi: 1.469, gti: 1.626, safeIndex: 69, risk: "Medium", usRank: 44 },
  { code: "CA", en: "Canada", cn: "加拿大", gpi: 1.491, gti: 1.87, safeIndex: 88, risk: "Low", usRank: 6 },
  { code: "NL", en: "Netherlands", cn: "荷蘭", gpi: 1.491, gti: 1.402, safeIndex: 75, risk: "Low", usRank: 11 },
  { code: "BE", en: "Belgium", cn: "比利時", gpi: 1.492, gti: 1.347, safeIndex: 70, risk: "Low", usRank: 10 },
  { code: "HU", en: "Hungary", cn: "匈牙利", gpi: 1.5, gti: null, safeIndex: 83, risk: "Low", usRank: 26 },
  { code: "AU", en: "Australia", cn: "澳大利亞", gpi: 1.505, gti: 1.973, safeIndex: 86, risk: "Low", usRank: 9 },
  { code: "HR", en: "Croatia", cn: "克羅埃西亞", gpi: 1.519, gti: null, safeIndex: 83, risk: "Low", usRank: 28 },
  { code: "DE", en: "Germany", cn: "德國", gpi: 1.533, gti: 4.748, safeIndex: 85, risk: "Medium", usRank: 17 },
  { code: "BT", en: "Bhutan", cn: "不丹", gpi: 1.536, gti: null, safeIndex: 70, risk: "Low", usRank: null },
  { code: "LT", en: "Lithuania", cn: "立陶宛", gpi: 1.558, gti: 0.423, safeIndex: 79, risk: "Low", usRank: 33 },
  { code: "LV", en: "Latvia", cn: "拉脫維亞", gpi: 1.558, gti: 0.423, safeIndex: 80, risk: "Low", usRank: 35 },
  { code: "EE", en: "Estonia", cn: "愛沙尼亞", gpi: 1.559, gti: null, safeIndex: 82, risk: "Low", usRank: 36 },
  { code: "ES", en: "Spain", cn: "西班牙", gpi: 1.578, gti: 1.256, safeIndex: 83, risk: "Medium", usRank: 21 },
  { code: "MU", en: "Mauritius", cn: "模裡西斯", gpi: 1.586, gti: null, safeIndex: 80, risk: "Low", usRank: null },
  { code: "QA", en: "Qatar", cn: "卡達", gpi: 1.593, gti: null, safeIndex: 84, risk: "Low", usRank: 24 },
  { code: "SK", en: "Slovakia", cn: "斯洛伐克", gpi: 1.609, gti: 1.023, safeIndex: 80, risk: "Low", usRank: 34 },
  { code: "BG", en: "Bulgaria", cn: "保加利亞", gpi: 1.61, gti: null, safeIndex: 80, risk: "Low", usRank: 37 },
  { code: "GB", en: "United Kingdom", cn: "英國", gpi: 1.634, gti: 2.639, safeIndex: 77, risk: "Low", usRank: 18 },
  { code: "KW", en: "Kuwait", cn: "科威特", gpi: 1.642, gti: null, safeIndex: 66, risk: "Low", usRank: 41 },
  { code: "NO", en: "Norway", cn: "挪威", gpi: 1.644, gti: 1.198, safeIndex: 85, risk: "Low", usRank: 2 },
  { code: "IT", en: "Italy", cn: "義大利", gpi: 1.662, gti: 0.929, safeIndex: 77, risk: "Medium", usRank: 23 },
  { code: "ME", en: "Montenegro", cn: "黑山", gpi: 1.685, gti: null, safeIndex: 70, risk: "Low", usRank: null },
  { code: "SE", en: "Sweden", cn: "瑞典", gpi: 1.709, gti: 1.842, safeIndex: 83, risk: "Low", usRank: 3 },
  { code: "PL", en: "Poland", cn: "波蘭", gpi: 1.713, gti: 1.962, safeIndex: 84, risk: "Low", usRank: 22 },
  { code: "MN", en: "Mongolia", cn: "蒙古", gpi: 1.719, gti: null, safeIndex: 71, risk: "Low", usRank: null },
  { code: "VN", en: "Vietnam", cn: "越南", gpi: 1.721, gti: null, safeIndex: 73, risk: "Low", usRank: 55 },
  { code: "RO", en: "Romania", cn: "羅馬尼亞", gpi: 1.721, gti: null, safeIndex: 80, risk: "Low", usRank: 40 },
  { code: "KR", en: "South Korea", cn: "韓國", gpi: 1.736, gti: 0.582, safeIndex: 82, risk: "Low", usRank: 29 },
  { code: "OM", en: "阿曼", cn: "阿曼", gpi: 1.738, gti: 2.927, safeIndex: 76, risk: "Low", usRank: 42 },
  { code: "BW", en: "Botswana", cn: "波札那", gpi: 1.743, gti: null, safeIndex: 77, risk: "Low", usRank: null },
  { code: "TL", en: "Timor-Leste", cn: "東帝汶", gpi: 1.758, gti: null, safeIndex: 48, risk: "High", usRank: null },
  { code: "GR", en: "Greece", cn: "希臘", gpi: 1.764, gti: 2.928, safeIndex: 73, risk: "Low", usRank: 20 },
  { code: "AR", en: "Argentina", cn: "阿根廷", gpi: 1.768, gti: 0.801, safeIndex: 70, risk: "Low", usRank: 53 },
  { code: "LA", en: "Laos", cn: "老撾", gpi: 1.783, gti: null, safeIndex: 51, risk: "Medium", usRank: null },
  { code: "UY", en: "Uruguay", cn: "烏拉圭", gpi: 1.784, gti: 0.059, safeIndex: 77, risk: "Low", usRank: 56 },
  { code: "ID", en: "Indonesia", cn: "印尼", gpi: 1.786, gti: 4.17, safeIndex: 58, risk: "Medium", usRank: 51 },
  { code: "NA", en: "Namibia", cn: "納米比亞", gpi: 1.789, gti: null, safeIndex: 71, risk: "Medium", usRank: null },
  { code: "MK", en: "North Macedonia", cn: "北馬其頓", gpi: 1.799, gti: null, safeIndex: 55, risk: "Low", usRank: null },
  { code: "AE", en: "United Arab Emirates", cn: "阿聯酋", gpi: 1.812, gti: 1.178, safeIndex: 79, risk: "Low", usRank: 25 },
  { code: "AL", en: "Albania", cn: "阿爾巴尼亞", gpi: 1.812, gti: null, safeIndex: 75, risk: "Low", usRank: null },
  { code: "CR", en: "Costa Rica", cn: "哥斯大黎加", gpi: 1.843, gti: null, safeIndex: 64, risk: "Medium", usRank: 48 },
  { code: "GM", en: "Gambia", cn: "甘比亞", gpi: 1.855, gti: null, safeIndex: 69, risk: "Medium", usRank: null },
  { code: "KZ", en: "Kazakhstan", cn: "哈薩克", gpi: 1.875, gti: null, safeIndex: 72, risk: "Low", usRank: 65 },
  { code: "SL", en: "Sierra Leone", cn: "獅子山", gpi: 1.887, gti: null, safeIndex: 50, risk: "Medium", usRank: null },
  { code: "AM", en: "Armenia", cn: "亞美尼亞", gpi: 1.893, gti: 0.72, safeIndex: 60, risk: "Low", usRank: null },
  { code: "MG", en: "Madagascar", cn: "馬達加斯加", gpi: 1.895, gti: null, safeIndex: 49, risk: "Medium", usRank: null },
  { code: "BA", en: "Bosnia and Herzegovina", cn: "波黑", gpi: 1.895, gti: 1.218, safeIndex: 48, risk: "Low", usRank: null },
  { code: "GH", en: "迦納", cn: "迦納", gpi: 1.898, gti: null, safeIndex: 73, risk: "Medium", usRank: 70 },
  { code: "CL", en: "智利", cn: "智利", gpi: 1.899, gti: 5.162, safeIndex: 79, risk: "Medium", usRank: 57 },
  { code: "ZM", en: "Zambia", cn: "尚比亞", gpi: 1.914, gti: null, safeIndex: 52, risk: "Medium", usRank: null },
  { code: "RS", en: "Serbia", cn: "塞爾維亞", gpi: 1.914, gti: 0.582, safeIndex: 77, risk: "Medium", usRank: 66 },
  { code: "MD", en: "Moldova", cn: "莫爾達瓦", gpi: 1.918, gti: null, safeIndex: 67, risk: "Medium", usRank: null },
  { code: "UZ", en: "Uzbekistan", cn: "烏茲別克斯坦", gpi: 1.926, gti: 0.233, safeIndex: 40, risk: "Medium", usRank: 71 },
  { code: "CY", en: "Cyprus", cn: "賽普勒斯", gpi: 1.933, gti: 0.347, safeIndex: 75, risk: "Low", usRank: 31 },
  { code: "SN", en: "Senegal", cn: "塞內加爾", gpi: 1.936, gti: 1.578, safeIndex: 45, risk: "High", usRank: null },
  { code: "LR", en: "Liberia", cn: "賴比瑞亞", gpi: 1.939, gti: null, safeIndex: 45, risk: "Medium", usRank: null },
  { code: "MW", en: "Malawi", cn: "馬拉威", gpi: 1.955, gti: null, safeIndex: null, risk: null, usRank: null },
  { code: "JO", en: "Jordan", cn: "約旦", gpi: 1.957, gti: 2.913, safeIndex: 53, risk: "Medium", usRank: 49 },
  { code: "TZ", en: "Tanzania", cn: "坦尚尼亞", gpi: 1.965, gti: 1.573, safeIndex: null, risk: null, usRank: null },
  { code: "FR", en: "France", cn: "法國", gpi: 1.967, gti: 2.712, safeIndex: 64, risk: "Medium", usRank: 30 },
  { code: "PY", en: "Paraguay", cn: "巴拉圭", gpi: 1.981, gti: 0.073, safeIndex: 45, risk: "Low", usRank: null },
  { code: "AO", en: "Angola", cn: "安哥拉", gpi: 1.987, gti: 1.657, safeIndex: 48, risk: "High", usRank: null },
  { code: "NP", en: "Nepal", cn: "尼泊爾", gpi: 1.987, gti: 1.113, safeIndex: 59, risk: "Medium", usRank: null },
  { code: "KG", en: "Kyrgyzstan", cn: "吉爾吉斯斯坦", gpi: 1.988, gti: null, safeIndex: 38, risk: "Medium", usRank: null },
  { code: "DO", en: "Dominican Republic", cn: "多明尼克", gpi: 1.996, gti: null, safeIndex: 54, risk: "Medium", usRank: 60 },
  { code: "TJ", en: "Tajikistan", cn: "塔吉克斯坦", gpi: 1.996, gti: 0.999, safeIndex: 38, risk: "Medium", usRank: null },
  { code: "TN", en: "Tunisia", cn: "突尼斯", gpi: 1.998, gti: 2.184, safeIndex: 53, risk: "Medium", usRank: 58 },
  { code: "GQ", en: "Equatorial Guinea", cn: "赤道幾內亞", gpi: 2.004, gti: null, safeIndex: 68, risk: "Medium", usRank: null },
  { code: "BO", en: "Bolivia", cn: "玻利維亞", gpi: 2.005, gti: null, safeIndex: 57, risk: "Low", usRank: null },
  { code: "PA", en: "Panama", cn: "巴拿馬", gpi: 2.006, gti: null, safeIndex: 65, risk: "Medium", usRank: 61 },
  { code: "MA", en: "Morocco", cn: "摩洛哥", gpi: 2.012, gti: null, safeIndex: 54, risk: "Medium", usRank: 45 },
  { code: "TH", en: "Thailand", cn: "泰國", gpi: 2.017, gti: 4.63, safeIndex: 48, risk: "Medium", usRank: 46 },
  { code: "KH", en: "Cambodia", cn: "柬埔寨", gpi: 2.019, gti: 0.423, safeIndex: 68, risk: "Low", usRank: 76 },
  { code: "TM", en: "Turkmenistan", cn: "土庫曼斯坦", gpi: 2.019, gti: null, safeIndex: 42, risk: "Medium", usRank: null },
  { code: "TT", en: "Trinidad and Tobago", cn: "千里達和多巴哥", gpi: 2.02, gti: null, safeIndex: 43, risk: "High", usRank: null },
  { code: "SA", en: "Saudi Arabia", cn: "沙烏地阿拉伯", gpi: 2.035, gti: 0.845, safeIndex: 46, risk: "Medium", usRank: 39 },
  { code: "RW", en: "Rwanda", cn: "盧旺達", gpi: 2.036, gti: null, safeIndex: 37, risk: "Low", usRank: null },
  { code: "DZ", en: "Algeria", cn: "阿爾及利亞", gpi: 2.042, gti: 2.415, safeIndex: 44, risk: "Medium", usRank: 64 },
  { code: "JM", en: "Jamaica", cn: "牙買加", gpi: 2.047, gti: null, safeIndex: 55, risk: "Medium", usRank: null },
  { code: "CI", en: "Ivory Coast", cn: "象牙海岸", gpi: 2.066, gti: 1.454, safeIndex: 37, risk: "Medium", usRank: null },
  { code: "AZ", en: "Azerbaijan", cn: "亞塞拜然", gpi: 2.067, gti: 0.233, safeIndex: 51, risk: "Medium", usRank: 59 },
  { code: "PE", en: "Peru", cn: "秘魯", gpi: 2.073, gti: 2.062, safeIndex: 50, risk: "Medium", usRank: 50 },
  { code: "LK", en: "Sri Lanka", cn: "斯裡蘭卡", gpi: 2.075, gti: null, safeIndex: 60, risk: "Medium", usRank: 73 },
  { code: "CN", en: "China", cn: "中國", gpi: 2.093, gti: 1.863, safeIndex: 66, risk: "Low", usRank: 54 },
  { code: "SZ", en: "Eswatini", cn: "史瓦濟蘭", gpi: 2.094, gti: 0.087, safeIndex: 47, risk: "Medium", usRank: null },
  { code: "BH", en: "Bahrain", cn: "巴林", gpi: 2.099, gti: 0.059, safeIndex: 46, risk: "Low", usRank: 38 },
  { code: "GW", en: "Guinea-Bissau", cn: "幾內亞比索", gpi: 2.112, gti: null, safeIndex: 36, risk: "Medium", usRank: null },
  { code: "CU", en: "Cuba", cn: "古巴", gpi: 2.123, gti: null, safeIndex: 47, risk: "Medium", usRank: null },
  { code: "CG", en: "Republic of the Congo", cn: "剛果(布)", gpi: 2.132, gti: null, safeIndex: 54, risk: "Medium", usRank: null },
  { code: "SV", en: "El Salvador", cn: "薩爾瓦多", gpi: 2.136, gti: null, safeIndex: 50, risk: "Medium", usRank: 67 },
  { code: "PH", en: "Philippines", cn: "菲律賓", gpi: 2.148, gti: 5.166, safeIndex: 47, risk: "Medium", usRank: 62 },
  { code: "GY", en: "Guyana", cn: "圭亞那", gpi: 2.149, gti: null, safeIndex: 43, risk: "Medium", usRank: null },
  { code: "EG", en: "Egypt", cn: "埃及", gpi: 2.157, gti: 4.416, safeIndex: 38, risk: "Medium", usRank: 52 },
  { code: "GT", en: "Guatemala", cn: "瓜地馬拉", gpi: 2.174, gti: null, safeIndex: 54, risk: "Medium", usRank: 74 },
  { code: "GE", en: "Georgia", cn: "格魯吉亞", gpi: 2.185, gti: null, safeIndex: 63, risk: "Low", usRank: null },
  { code: "MR", en: "Mauritania", cn: "茅利塔尼亞", gpi: 2.204, gti: null, safeIndex: 35, risk: "High", usRank: null },
  { code: "NI", en: "Nicaragua", cn: "尼加拉瓜", gpi: 2.207, gti: null, safeIndex: 46, risk: "Medium", usRank: null },
  { code: "BJ", en: "Benin", cn: "貝南", gpi: 2.211, gti: 4.802, safeIndex: 45, risk: "Medium", usRank: null },
  { code: "UG", en: "Uganda", cn: "烏幹達", gpi: 2.217, gti: 3.702, safeIndex: 49, risk: "Medium", usRank: null },
  { code: "ZW", en: "Zimbabwe", cn: "辛巴威", gpi: 2.223, gti: null, safeIndex: 53, risk: "Medium", usRank: 69 },
  { code: "IN", en: "India", cn: "印度", gpi: 2.229, gti: 6.411, safeIndex: 47, risk: "Medium", usRank: 82 },
  { code: "PG", en: "Papua New Guinea", cn: "巴布亞紐幾內亞", gpi: 2.23, gti: null, safeIndex: 47, risk: "Medium", usRank: null },
  { code: "GA", en: "Gabon", cn: "加蓬", gpi: 2.238, gti: null, safeIndex: 45, risk: "High", usRank: null },
  { code: "GN", en: "Guinea", cn: "幾內亞", gpi: 2.253, gti: null, safeIndex: 39, risk: "Medium", usRank: null },
  { code: "BY", en: "Belarus", cn: "白俄羅斯", gpi: 2.267, gti: 0.233, safeIndex: 77, risk: "Low", usRank: 78 },
  { code: "LS", en: "Lesotho", cn: "賴索托", gpi: 2.267, gti: null, safeIndex: 47, risk: "Medium", usRank: null },
  { code: "MZ", en: "Mozambique", cn: "莫三比克", gpi: 2.273, gti: 6.251, safeIndex: 46, risk: "High", usRank: null },
  { code: "DJ", en: "Djibouti", cn: "吉布地", gpi: 2.276, gti: 1.461, safeIndex: 38, risk: "Medium", usRank: null },
  { code: "BD", en: "Bangladesh", cn: "孟加拉", gpi: 2.318, gti: 3.03, safeIndex: 49, risk: "Medium", usRank: 75 },
  { code: "ZA", en: "South Africa", cn: "南非", gpi: 2.347, gti: null, safeIndex: 48, risk: "Medium", usRank: 83 },
  { code: "HN", en: "Honduras", cn: "洪都拉斯", gpi: 2.347, gti: null, safeIndex: 49, risk: "Medium", usRank: 63 },
  { code: "TG", en: "Togo", cn: "多哥", gpi: 2.381, gti: 5.004, safeIndex: 69, risk: "Medium", usRank: null },
  { code: "KE", en: "Kenya", cn: "肯亞", gpi: 2.392, gti: 5.366, safeIndex: 45, risk: "Medium", usRank: 72 },
  { code: "US", en: "United States", cn: "美國", gpi: 2.443, gti: 3.517, safeIndex: 68, risk: "Low", usRank: 47 },
  { code: "EC", en: "Ecuador", cn: "厄瓜多爾", gpi: 2.459, gti: 1.55, safeIndex: 55, risk: "Low", usRank: 79 },
  { code: "BR", en: "Brazil", cn: "巴西", gpi: 2.472, gti: 1.43, safeIndex: 52, risk: "Medium", usRank: 85 },
  { code: "LY", en: "Libya", cn: "利比亞", gpi: 2.478, gti: 1.612, safeIndex: 21, risk: "High", usRank: null },
  { code: "ER", en: "Eritrea", cn: "厄立特裡亞", gpi: 2.542, gti: null, safeIndex: 32, risk: "Medium", usRank: null },
  { code: "BI", en: "Burundi", cn: "布隆迪", gpi: 2.574, gti: 4.043, safeIndex: 30, risk: "High", usRank: null },
  { code: "TD", en: "Chad", cn: "查德", gpi: 2.593, gti: 5.032, safeIndex: 32, risk: "High", usRank: null },
  { code: "MX", en: "Mexico", cn: "墨西哥", gpi: 2.636, gti: 0.582, safeIndex: 65, risk: "Medium", usRank: 81 },
  { code: "LB", en: "Lebanon", cn: "黎巴嫩", gpi: 2.674, gti: 1.237, safeIndex: 35, risk: "High", usRank: 87 },
  { code: "CM", en: "Cameroon", cn: "喀麥隆", gpi: 2.683, gti: 6.944, safeIndex: 36, risk: "High", usRank: 84 },
  { code: "ET", en: "Ethiopia", cn: "衣索比亞", gpi: 2.688, gti: 0.787, safeIndex: 41, risk: "High", usRank: null },
  { code: "VE", en: "Venezuela", cn: "委內瑞拉", gpi: 2.692, gti: 0.71, safeIndex: 33, risk: "High", usRank: null },
  { code: "CO", en: "Colombia", cn: "哥倫比亞", gpi: 2.695, gti: 6.381, safeIndex: 42, risk: "Medium", usRank: 86 },
  { code: "HT", en: "Haiti", cn: "海地", gpi: 2.731, gti: null, safeIndex: 42, risk: "High", usRank: null },
  { code: "IR", en: "Iran", cn: "伊朗", gpi: 2.75, gti: 6.056, safeIndex: 35, risk: "High", usRank: 77 },
  { code: "NE", en: "Niger", cn: "尼日爾", gpi: 2.759, gti: 7.776, safeIndex: 37, risk: "High", usRank: null },
  { code: "PK", en: "Pakistan", cn: "巴基斯坦", gpi: 2.797, gti: 8.374, safeIndex: 26, risk: "High", usRank: null },
  { code: "PS", en: "Palestine", cn: "巴勒斯坦", gpi: 2.811, gti: 4.93, safeIndex: null, risk: null, usRank: null },
  { code: "TR", en: "Turkey", cn: "土耳其", gpi: 2.852, gti: 3.968, safeIndex: 45, risk: "Medium", usRank: 43 },
  { code: "IQ", en: "Iraq", cn: "伊拉克", gpi: 2.862, gti: 6.582, safeIndex: 14, risk: "High", usRank: null },
  { code: "NG", en: "Nigeria", cn: "奈及利亞", gpi: 2.869, gti: 7.658, safeIndex: 33, risk: "Medium", usRank: null },
  { code: "KP", en: "North Korea", cn: "朝鮮", gpi: 2.911, gti: null, safeIndex: 21, risk: "High", usRank: null },
  { code: "CF", en: "Central African Republic", cn: "中非", gpi: 2.912, gti: 0.957, safeIndex: 32, risk: "High", usRank: null },
  { code: "SO", en: "Somalia", cn: "索馬裡", gpi: 2.983, gti: 7.614, safeIndex: 16, risk: "High", usRank: null },
  { code: "BF", en: "Burkina Faso", cn: "布吉納法索", gpi: 3.016, gti: 8.581, safeIndex: 41, risk: "Medium", usRank: null },
  { code: "MM", en: "Myanmar", cn: "緬甸", gpi: 3.045, gti: 6.929, safeIndex: 39, risk: "Medium", usRank: 68 },
  { code: "ML", en: "Mali", cn: "馬裡", gpi: 3.061, gti: 7.907, safeIndex: 31, risk: "High", usRank: null },
  { code: "IL", en: "Israel", cn: "以色列", gpi: 3.108, gti: 7.463, safeIndex: 60, risk: "Medium", usRank: 88 },
  { code: "SS", en: "South Sudan", cn: "南蘇丹", gpi: 3.117, gti: null, safeIndex: 10, risk: "High", usRank: null },
  { code: "SY", en: "Syria", cn: "敘利亞", gpi: 3.184, gti: 8.006, safeIndex: 10, risk: "High", usRank: null },
  { code: "AF", en: "Afghanistan", cn: "阿富汗", gpi: 3.229, gti: 7.262, safeIndex: 14, risk: "High", usRank: null },
  { code: "YE", en: "Yemen", cn: "葉門", gpi: 3.262, gti: 5.08, safeIndex: 10, risk: "High", usRank: null },
  { code: "CD", en: "DR Congo", cn: "剛果(金)", gpi: 3.292, gti: 6.768, safeIndex: 21, risk: "High", usRank: null },
  { code: "SD", en: "Sudan", cn: "蘇丹", gpi: 3.323, gti: null, safeIndex: 55, risk: "High", usRank: null },
  { code: "UA", en: "Ukraine", cn: "烏克蘭", gpi: 3.434, gti: 2.003, safeIndex: 30, risk: "High", usRank: 89 },
  { code: "RU", en: "Russia", cn: "俄羅斯", gpi: 3.441, gti: 6.267, safeIndex: 34, risk: "High", usRank: 80 },
  { code: "PR", en: "Puerto Rico", cn: "波多黎各", gpi: null, gti: null, safeIndex: 34, risk: "Medium", usRank: null },
  { code: "FJ", en: "Fiji", cn: "斐濟", gpi: null, gti: null, safeIndex: 70, risk: "Low", usRank: null },
  { code: "LU", en: "Luxembourg", cn: "盧森堡", gpi: null, gti: null, safeIndex: 74, risk: "Low", usRank: 14 },
  { code: "SR", en: "Suriname", cn: "蘇利南", gpi: null, gti: null, safeIndex: 62, risk: "Medium", usRank: null },
  { code: "MT", en: "Malta", cn: "馬爾他", gpi: null, gti: null, safeIndex: 78, risk: "Low", usRank: null },
  { code: "MV", en: "Maldives", cn: "馬爾地夫", gpi: null, gti: null, safeIndex: 46, risk: "Low", usRank: null },
  { code: "BN", en: "Brunei", cn: "汶萊", gpi: null, gti: null, safeIndex: 80, risk: "Low", usRank: null },
  { code: "BZ", en: "Belize", cn: "貝裡斯", gpi: null, gti: null, safeIndex: 43, risk: "Medium", usRank: null },
  { code: "BS", en: "Bahamas", cn: "巴哈馬", gpi: null, gti: null, safeIndex: 49, risk: "Low", usRank: null },
  { code: "VU", en: "Vanuatu", cn: "瓦努阿圖", gpi: null, gti: null, safeIndex: 70, risk: "Low", usRank: null },
  { code: "PF", en: "French Polynesia", cn: "法屬波利尼西亞", gpi: null, gti: null, safeIndex: 92, risk: "Low", usRank: null },
  { code: "BB", en: "Barbados", cn: "巴貝多", gpi: null, gti: null, safeIndex: 80, risk: "Low", usRank: null },
  { code: "WS", en: "Samoa", cn: "薩摩亞", gpi: null, gti: null, safeIndex: 70, risk: "Low", usRank: null },
  { code: "CW", en: "Curacao", cn: "庫拉索", gpi: null, gti: null, safeIndex: 80, risk: "Low", usRank: null },
  { code: "LC", en: "Saint Lucia", cn: "聖露西亞", gpi: null, gti: null, safeIndex: 70, risk: "Low", usRank: null },
  { code: "SC", en: "Seychelles", cn: "塞席爾", gpi: null, gti: null, safeIndex: 80, risk: "Low", usRank: null },
  { code: "GD", en: "Grenada", cn: "格瑞那達", gpi: null, gti: null, safeIndex: 80, risk: "Low", usRank: null },
  { code: "AW", en: "Aruba", cn: "阿魯巴", gpi: null, gti: null, safeIndex: 90, risk: "Low", usRank: null },
  { code: "TO", en: "Tonga", cn: "東加", gpi: null, gti: null, safeIndex: 70, risk: "Low", usRank: null },
  { code: "KY", en: "Cayman Islands", cn: "開曼群島", gpi: null, gti: null, safeIndex: 50, risk: "Medium", usRank: null },
  { code: "DM", en: "Dominica", cn: "多明尼克", gpi: null, gti: null, safeIndex: 80, risk: "Low", usRank: null },
  { code: "BM", en: "Bermuda", cn: "百慕大", gpi: null, gti: null, safeIndex: 90, risk: "Low", usRank: null },
  { code: "GL", en: "Greenland", cn: "格陵蘭", gpi: null, gti: null, safeIndex: 80, risk: "Low", usRank: null },
  { code: "KN", en: "Saint Kitts and Nevis", cn: "聖基茨和尼維斯", gpi: null, gti: null, safeIndex: 70, risk: "Low", usRank: null },
  { code: "GI", en: "Gibraltar", cn: "直布羅陀", gpi: null, gti: null, safeIndex: 90, risk: "Low", usRank: null },
  { code: "LI", en: "Liechtenstein", cn: "列支敦士登", gpi: null, gti: null, safeIndex: 89, risk: "Low", usRank: null },
  { code: "VG", en: "British Virgin Islands", cn: "英屬維京群島", gpi: null, gti: null, safeIndex: 89, risk: "Low", usRank: null },
  { code: "MC", en: "Monaco", cn: "摩納哥", gpi: null, gti: null, safeIndex: 88, risk: "Low", usRank: null },
  { code: "PW", en: "Palau", cn: "帛琉", gpi: null, gti: null, safeIndex: 80, risk: "Low", usRank: null },
  { code: "AI", en: "Anguilla", cn: "安圭拉", gpi: null, gti: null, safeIndex: 70, risk: "Low", usRank: null },
  { code: "NR", en: "Nauru", cn: "諾魯", gpi: null, gti: null, safeIndex: 80, risk: "Low", usRank: null },
  { code: "MS", en: "Montserrat", cn: "蒙瑟拉特", gpi: null, gti: null, safeIndex: 70, risk: "Low", usRank: null }
];
